using System.Text;
using AtomUI.City.Generators.Common;

namespace AtomUI.City.Generators.Presentation;

public static class PresentationViewRegistrarSourceBuilder
{
    public static string Build(PresentationViewManifest manifest)
    {
        if (manifest is null)
        {
            throw new ArgumentNullException(nameof(manifest));
        }

        var typeName = GeneratedCodeNames.CreateRegistrarTypeName(GeneratorFeature.Presentation, "ViewRegistrar");
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.Append("namespace ").Append(typeName.Namespace).AppendLine(";");
        builder.AppendLine();
        builder.Append("public static class ").Append(typeName.Name).AppendLine();
        builder.AppendLine("{");
        builder.AppendLine("    public static void RegisterViews(global::AtomUI.City.Presentation.IViewRegistry registry)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(registry);");

        foreach (var view in manifest.Views)
        {
            AppendViewRegistration(builder, view);
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void AppendViewRegistration(
        StringBuilder builder,
        PresentationViewManifestEntry view)
    {
        builder.AppendLine();
        builder.AppendLine("        registry.Register(");
        builder.AppendLine("            new global::AtomUI.City.Presentation.ViewDescriptor(");
        builder.Append("                typeof(").Append(ToGlobalTypeName(view.ViewModelTypeName)).AppendLine("),");
        builder.Append("                typeof(").Append(ToGlobalTypeName(view.ViewTypeName)).AppendLine("),");
        builder.Append("                viewKey: ").Append(ToStringLiteral(view.ViewKey)).AppendLine(",");
        builder
            .Append("                static context => new ")
            .Append(ToGlobalTypeName(view.ViewTypeName))
            .AppendLine("(),");
        builder.Append("                pluginId: ").Append(ToStringLiteral(view.PluginId)).AppendLine(",");
        builder.Append("                contributionId: ").Append(ToStringLiteral(view.ContributionId)).AppendLine("));");
    }

    private static string ToGlobalTypeName(string typeName)
    {
        return "global::" + typeName;
    }

    private static string ToStringLiteral(string? value)
    {
        return value is null ? "null" : "@\"" + value.Replace("\"", "\"\"") + "\"";
    }
}
